term xterm-kitty
enable_audio_bell no

font_family      IosevkaTerm Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

scrollback_lines 5000
wheel_scroll_multiplier 3.0

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

map ctrl+shift+t new_tab
map ctrl+shift+j next_tab
map ctrl+shift+k previous_tab
map ctrl+shift+w close_tab
map ctrl+enter send_text all \x1b[13;5u
map shift+enter send_text all \x1b[13;2u

clipboard_control write-clipboard write-primary

# Catppuccin Mocha theme.
include current-theme.conf
