# Visual settings.
blur=0
blur_layer=0
shadows=0
layer_shadows=0
border_radius=0
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0

animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1
animation_duration_move=150
animation_duration_open=150
animation_duration_tag=150
animation_duration_close=150
animation_duration_focus=0
animation_curve_open=0.1,0,0.1,1
animation_curve_move=0.1,0,0.1,1
animation_curve_tag=0.1,0,0.1,1
animation_curve_close=0.1,0,0.1,1
animation_curve_focus=0.1,0,0.1,1
animation_curve_opafadeout=0.1,0,0.1,1
animation_curve_opafadein=0.1,0,0.1,1

new_is_master=1
default_mfact=0.5
default_nmaster=1
smartgaps=0
circle_layout=tile,scroller,monocle

hotarea_size=10
enable_hotarea=1
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=0
sloppyfocus=0
warpcursor=0
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
drag_tile_to_tile=1

gappih=5
gappiv=5
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=1
rootcolor=0x111111ff
bordercolor=0x595959aa
focuscolor=0xffffffee
maximizescreencolor=0xffffffee
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

# Keep a simple tiled layout across tags.
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# Layer animation tweaks.
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
