# Float helper applications.
windowrule=isfloating:1,appid:^pavucontrol$
windowrule=isfloating:1,appid:^helvum$
windowrule=isfloating:1,appid:^gnome-power-statistics$
windowrule=isfloating:1,appid:^nm-connection-editor$

# Quickshell popup helper.
windowrule=isfloating:1,width:800,height:500,offsetx:0,offsety:0,title:^quickshell$
