exec-once=$HOME/.local/bin/waybar
exec-once=$HOME/.local/bin/dunst
exec-once=$HOME/.local/bin/swayidle -w -C $HOME/.config/swayidle/config
exec-once=$HOME/.local/bin/swaybg -i ~/Pictures/wallpapers/wallpaper.png
