dpi-aware=no
icon-theme=Adwaita
width=80
font=IosevkaTerm:size=12
line-height=15
fields=name,generic,comment,categories,filename,keywords
prompt="❯   "
exit-on-keyboard-focus-loss=no

[colors]
# Matches with waybar colours
background=1e1e2eff
text=cdd6f4ff
match=ed8796ff
selection=6c7086ff
selection-text=cad3f5ff
selection-match=ed8796ff
border=ffffffee

[border]
radius=0

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
# Unbind delete-next-line from Control+k
delete-line=Shift+Mod1+d
# Bind navigation
prev=Control+k
next=Control+j
