[Appearance]
color_scheme_path=~/.config/qt6ct/colors/catppuccin-mocha-red.conf
custom_palette=true
icon_theme=Adwaita
style=Fusion

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\x1a\0\0\x4y\0\0\0\0\0\0\0\0\0\0\x4\x1a\0\0\x4y\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x4\x1a\0\0\x4y)
