#!/usr/bin/env sh
set -eu

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=Mango
export XDG_SESSION_DESKTOP=Mango

export PATH="$HOME/.local/bin:$HOME/.local/scripts:$PATH"

exec mango "$@"
